// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmPM7E3U7MATNatHG8tHZ582OXxhdiFLo',
    appId: '1:850572777754:web:93ee5076aed9b2a23d74a3',
    messagingSenderId: '850572777754',
    projectId: 'shopping-app-85ace',
    authDomain: 'shopping-app-85ace.firebaseapp.com',
    storageBucket: 'shopping-app-85ace.firebasestorage.app',
    measurementId: 'G-29Y3YCEFM8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYLalmh80Nx4CmhMNLbnRs5FcmSFLyJfw',
    appId: '1:850572777754:android:a35b4757318140a23d74a3',
    messagingSenderId: '850572777754',
    projectId: 'shopping-app-85ace',
    storageBucket: 'shopping-app-85ace.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP5JPWR-UL_oEhsUPr4wNmAHDMhRk8_SM',
    appId: '1:850572777754:ios:9b3a524566b3b6953d74a3',
    messagingSenderId: '850572777754',
    projectId: 'shopping-app-85ace',
    storageBucket: 'shopping-app-85ace.firebasestorage.app',
    iosBundleId: 'com.example.simpleShoppingApp',
  );
}
